# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  username: postgres
  password: shaina # from psql setup, see Postgresql

# development:
#   <<: *common
#   database: wtadb

development:
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 5
    timeout: 5000


production:
  <<: *common
  database: myapp_production